export const themes = {
  "light": {
    '--bg-base-color': "#EFF6FC",
    '--bg-main-color': "#6E00FF",
    '--bg-support-color': "#FFF",
    '--main-hover': "lightgreen",
    '--ui-main-color': "lightgreen",
    '--ui-danger-color': "tomato",
    '--online-color': "rgb(174, 174, 90)",
    '--offline-color': "tomato",
    '--text-light-color': "#fff",
    '--active-border': "#F3B559",
    '--button-hover': "#3e3ebc",
    '--active-tab': "rgba(0, 0, 0, 0.1)",
    '--text-dark-color': "black",
    '--text-support-color': "#303030",
    '--icon-color': "rgb(173, 173, 173)",
    '--message-self-color': "rgb(236, 255, 215)",
    '--message-recipient-color': "#E7E7E7",
    '--date-color': "#707070",
    '--group-sender-color': "#6E00FF",
    '--separate-color': "#dbd2d2",
    '--form-wrap-color': "#575f71",
    '--placeholder-color': "#999",
    '--link-color': "#3e3ebc",
    '--status-border-color': "white",
    '--box-shadow': "rgb(195,227,247)",
    '--text-main-color': "#000",
    '--loader-color': "#6E00FF"
  },

  "dark": {
    '--bg-main-color': "#040303",
    '--bg-support-color': "#1f1d1d",
    '--bg-base-color': "#1e252c",
    '--main-hover': "lightgreen",
    '--ui-main-color': "lightgreen",
    '--ui-danger-color': "tomato",
    '--online-color': "rgb(174, 174, 90)",
    '--offline-color': "tomato",
    '--text-light-color': "#fff",
    '--active-border': "lightgreen",
    '--button-hover': "#3e3ebc",
    '--active-tab': "#34373a",
    '--text-dark-color': "black",
    '--text-support-color': "#fff",
    '--icon-color': "#fff",
    '--message-self-color': "rgb(236, 255, 215)",
    '--message-recipient-color': "#232121",
    '--date-color': "#707070",
    '--group-sender-color': "lightgreen",
    '--separate-color': "#2c2a2a",
    '--form-wrap-color': "#575f71",
    '--placeholder-color': "#999",
    '--link-color': "#3e3ebc",
    '--status-border-color': "white",
    '--box-shadow': "rgb(20, 33, 42)",
    '--text-main-color': "#fff",
    '--loader-color': "lightgreen"
  }
}